#!groovy

def e2eContainerName = "cye2e-${job_name}${env.BUILD_NUMBER}"
def rancherContainerName = "rancher-${job_name}${env.BUILD_NUMBER}"
def DEPENDENCIES_INSTALLED = false

def branch = "master"
if ("${env.branch}" != "null" && "${env.branch}" != "") {
  branch = "${env.branch}"
}

if ("${env.CORRAL_PACKAGES_REPO}" != "null" && "${env.CORRAL_PACKAGES_REPO}" != "") {
      corralRepo = "${env.CORRAL_PACKAGES_REPO}"
}

if ("${env.CORRAL_PACKAGES_BRANCH}" != "null" && "${env.CORRAL_PACKAGES_BRANCH}" != "") {
      corralBranch = "${env.CORRAL_PACKAGES_BRANCH}"
}

node {
  wrap([$class: 'AnsiColorBuildWrapper', 'colorMapName': 'XTerm', 'defaultFg': 2, 'defaultBg':1]) {
    withFolderProperties {
      paramsMap = []
      params.each {
        paramsMap << "$it.key=$it.value"
      }
      withCredentials([ string(credentialsId: 'AWS_ACCESS_KEY_ID', variable: 'AWS_ACCESS_KEY_ID'),
                        string(credentialsId: 'AWS_SECRET_ACCESS_KEY', variable: 'AWS_SECRET_ACCESS_KEY')]) {
      withEnv(paramsMap) {
            stage('Checkout') {
            deleteDir()
            checkout([
                        $class: 'GitSCM',
                        branches: [[name: "*/${branch}"]],
                        extensions: scm.extensions + [[$class: 'CleanCheckout']],
                        userRemoteConfigs: scm.userRemoteConfigs
                    ])
            dir('./corral-packages') {
                checkout([
                  $class: 'GitSCM',
                  branches: [[name: "*/${corralBranch}"]],
                  extensions: scm.extensions + [[$class: 'CleanCheckout']],
                  userRemoteConfigs: [[url: corralRepo]]
                ])
                def ciFilename = "ui-ci-node.yaml"
                def ciConfigContents = env.CORRAL_PACKAGE_CONFIG
                if (ciConfigContents != null) {
                    writeFile file: "./packages/aws/"+ciFilename, text: ciConfigContents
                }
            }
          }
          try {
            stage('Initialize') {
                sh 'jenkins/init.sh'
                sh 'jenkins/generate_env.sh'
            }
          } catch (err) {
              echo "Error: " + err
              currentBuild.result = 'FAILURE'
              error()
          }
          try {
            stage('Setup Dependencies') {
                sh "jenkins/sshexec.sh \"dashboard/jenkins/setup.sh\""
            }
          } catch (err) {
              echo "Error: " + err
              currentBuild.result = 'FAILURE'
              error()
          }
          try {
            stage('Run E2E Tests') {
              sh "jenkins/sshexec.sh \"dashboard/jenkins/run.sh\""
             }
          } catch (err) {
              echo "Error: " + err
              currentBuild.result = 'FAILURE'
          }
          try {
            stage('Grab Results') {
              sh "jenkins/scpget.sh dashboard/results.xml"
              sh "find . -type f -iname *.xml"
            }
          } catch(err) {
              echo "Error: " + err
          }
          try {
            stage('Clean Test Environment') {  
              sh "./corral delete ci"
            }
          } catch(err) {
            echo "Error: " + err
          }
          try {
            stage('Test Report') {
              step([$class: 'JUnitResultArchiver', testResults: '**/results.xml'])
            }
          }
          catch(err) {
            echo "Error: " + err
          }
        }
      }
    }
  }
}