#!/usr/bin/env bash
# configure.sh — Generates ~/.env consumed by the Docker test container.
set -euo pipefail

ENV_FILE="${HOME}/.env"
cat > "${ENV_FILE}" <<EOF
CYPRESS_VIDEO=false
CYPRESS_VIEWPORT_WIDTH=1000
CYPRESS_VIEWPORT_HEIGHT=660
TEST_BASE_URL=https://${RANCHER_HOST:-}/dashboard
TEST_USERNAME=${RANCHER_USERNAME:-admin}
TEST_PASSWORD=${RANCHER_PASSWORD:-password}
TEST_SKIP_SETUP=true
TEST_SKIP=setup
AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
AZURE_CLIENT_ID=${AZURE_CLIENT_ID:-}
AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET:-}
AZURE_AKS_SUBSCRIPTION_ID=${AZURE_AKS_SUBSCRIPTION_ID:-}
GKE_SERVICE_ACCOUNT=${GKE_SERVICE_ACCOUNT:-}
CUSTOM_NODE_IP=${CUSTOM_NODE_IP:-}
CUSTOM_NODE_KEY=${CUSTOM_NODE_KEY:-}
PERCY_TOKEN=${PERCY_TOKEN:-}
QASE_REPORT=${QASE_REPORT:-false}
QASE_PROJECT=${QASE_PROJECT:-SANDBOX}
QASE_AUTOMATION_TOKEN=${QASE_AUTOMATION_TOKEN:-}
RANCHER_IMAGE_TAG=${RANCHER_IMAGE_TAG:-unknown}
RANCHER_VERSION=${RANCHER_VERSION:-}
EOF

echo "[configure] Wrote ${ENV_FILE}"
